---
title: "R Notebook for Zygomaticus activation through facial neuromuscular electric stimulation (fNMES) induces happiness perception in ambiguous facial expressions and affects neural correlates of face processing"
author: Themis Efthimiou
output:
  html_document:
    df_print: paged
---

```{r}
# For the paper:
#   Themis Nikolas Efthimiou, Joshua Baker, Alasdair Clarke, Arthur Elsenaar, Marc Mehu, Sebastian Korb, Zygomaticus activation through facial neuromuscular electrical stimulation (fNMES) induces happiness perception in ambiguous facial expressions and affects neural correlates of face processing, Social Cognitive and Affective Neuroscience, Volume 19, Issue 1, 2024, nsae013, https://doi.org/10.1093/scan/nsae013
```

```{r Setup}
# Libraries
pacman::p_load(tidyverse, lme4, lmerTest, performance, emmeans)

# Clear all
rm(list=ls())

# load in the function to export PSEs there are two functions exteact_i (for individual participants) and extract_g (for group pses)
source("./functions.R")

# set some globals
options(digits = 3, mc.cores = 8, scipen = 999)
```

```{r Import data, message=FALSE, warning=FALSE}
dat <- read_csv("./Data/df_without_eeg.csv") %>% left_join(read_csv('./Data/openface_averaged.csv'))
```

```{r}
# remove fNMES only trials, trials where participants did not respond, and trials where RTs were < 100 ms or >3SD*mean
dat_b <- dat %>% 
  filter(emo != 'none' & emotion != '999' & response != 'miss' & outlier_RT != '1') %>% 
  mutate(
    emotion = as.numeric(emotion),
    # Change participant responses to numbers happy = 1, sad = 0
    response = factor(response, levels = c('sad', 'happy')),
    response_n = if_else(response == "happy", 1, 0),
    nmes = factor(nmes, levels = c('off', 'on')))
```

```{r}
fit <-
  lme4::glmer(response_n ~ emotion * nmes +
                (emotion + nmes | participant),
              family = binomial(link = "logit"),
              data = dat_b,
              control = glmerControl(optimizer = "bobyqa"))
```

```{r check fit}
summary(fit)
check_model(fit)
performance(fit)
round(lme4::confint.merMod(fit, method = 'Wald'), 2)
```

```{r Extract PSEs}
grp_pses <- extract_g_PSE(fit)
ind_pses <- extract_i_PSE(fit)
```

```{r Fit ambiguity}
fit_ambiguity <- dat_b %>% 
  lme4::glmer(response_n ~ 
                emotion +
                nmes + 
                ambiguity + 
                emotion : nmes + 
                emotion : ambiguity +
                nmes : ambiguity +
                (1 | participant),
              family = binomial(link = "logit"),
              data = .,
              control = glmerControl(optimizer = "bobyqa"))
```

```{r check fit ambiguity}
summary(fit_ambiguity)
check_model(fit_ambiguity)
performance(fit_ambiguity)
round(lme4::confint.merMod(fit_ambiguity, method = 'Wald'), 2)
```

```{r Model with covariates from survey data 45 subs}
cols_to_scale <- c("emotion", 
                   "discomfort", "EQ", "ASQ", 
                   "MAIA_Noticing", "MAIA_nDistracting", "MAIA_nWorrying", 
                   "MAIA_AttReg", "MAIA_EmoAwa", "MAIA_SReg", 
                   "MAIA_listening", "MAIA_trusting", 
                   "Pos_aff_1", "Neg_aff_1",
                   "rate_smile", "discomfort", "AU12",
                   "Belief_rating")

dat_cov <- dat_b %>%
  filter(!TestSum >= 2) %>% 
  mutate_at(vars(cols_to_scale),
            ~ scale(., center = TRUE, scale = TRUE))

fit_covs <- dat_cov %>% 
  lme4::glmer(response_n ~ emotion * nmes +
              ASQ + EQ + 
              MAIA_Noticing + MAIA_nWorrying +
              MAIA_AttReg + MAIA_EmoAwa +
              MAIA_nDistracting + MAIA_SReg + 
              MAIA_listening + MAIA_trusting +
              (emotion + nmes | participant),
            family = binomial(link = "logit"),
            data = .,)

# model summary
summary(fit_covs)
check_model(fit_covs)
performance(fit_covs)
round(lme4::confint.merMod(fit_covs, method = 'Wald'), 2)
```

```{r Model with covariates from experiment data 41 subs}
fit_covs_2 <- dat_cov %>% 
  lme4::glmer(response_n ~ emotion * nmes +
                Pos_aff_1 + Neg_aff_1 + discomfort + 
                (emotion + nmes | participant),
              family = binomial(link = "logit"),
              data = .,)

# model summary
summary(fit_covs_2)
check_model(fit_covs_2)
performance(fit_covs_2)
round(lme4::confint.merMod(fit_covs_2, method = 'Wald'), 2)
```

```{r EEG analysis setup}
dat2 <- read_csv('../Data/df_eeg.csv') %>% 
  mutate(participant = as.factor(participant),
         nmes = as.factor(nmes),
         trial = as.numeric(trial)) 

dat2 <- merge(dat, dat2, by = c('participant', 'trial', 'nmes', 'emo', 'emotion'))

dat2 %>% 
  mutate(gender = as.factor(gender)) %>% 
  group_by(gender) %>% 
  summarise(participant = n_distinct(participant), 
            gender = unique(gender),
            age_M = mean(age), 
            aged_SD = sd(age))

dat2 <- dat2 %>% 
  mutate(
    emotion = as.factor(emotion),
    nmes = factor(nmes, levels = c('off', 'on')) )

# allow for Type III Sums of Square
options(contrasts = c('contr.sum', 'contr.poly'))
```

```{r ERP - P100}
fit_P1 <-
  dat2 %>% 
  select(participant, emotion, emo, nmes, P1, quality_P1) %>% 
  filter(quality_P1 == 0) %>% 
  group_by(participant) %>% 
  mutate(pure_nmes = mean(P1[emo == 'none'])) %>% 
  mutate(P1 = ifelse(nmes == 'on', P1 - pure_nmes, P1)) %>% 
  filter(emotion != '999') %>% 
  mutate(emotion = as.factor(emotion),
         emotion = droplevels(emotion),
         participant = as.factor(participant)) %>%
  group_by(participant, emotion, nmes) %>% 
  summarise(P1 = mean(P1)) %>% 
  lmer(P1 ~ emotion * nmes + (1 | participant), data = .)

summary(fit_P1)
check_model(fit_P1)
performance(fit_P1)
round(confint(fit_P1, level = 0.95), 2)

anova(lmer_P100, type = 'III')
emmeans(lmer_P100, pairwise ~ nmes)
```

```{r ERP - N170}
fit_n170 <- dat2 %>% 
  filter(quality_N170_left == 0 & quality_N170_right == 0) %>% 
  mutate(N170 = rowMeans(select(., c(N170_left, N170_right)))) %>%
  group_by(participant) %>% 
  mutate(pure_nmes = mean(N170[emo == 'none'])) %>%
  mutate(N170 = ifelse(nmes == 'on', N170 - pure_nmes, N170)) %>% 
  filter(emotion != '999') %>% 
  mutate(emotion = as.factor(emotion),
         emotion = droplevels(emotion),
         participant = as.factor(participant)) %>%  
  group_by(emotion, nmes, participant) %>% 
  summarise(N170 = mean(N170)) %>% 
  lmer(N170 ~ emotion * nmes + (1 | participant), data = .)

summary(fit_n170)
check_model(fit_n170)
performance(fit_n170)
round(confint(fit_n170, level = 0.95), 2)

# descriptives
emmeans(fit_n170, pairwise ~ nmes) %>% confint()
```

```{r ERP - LPP}
fit_LPP <- dat2 %>% 
  ungroup %>% 
  filter(quality_LPP == 0) %>% 
  group_by(participant) %>% 
  mutate(pure_nmes = mean(LPP[emo == 'none'])) %>% 
  mutate(LPP = ifelse(nmes == 'on', LPP - pure_nmes, LPP)) %>% 
  filter(emotion != '999') %>% 
  mutate(emotion = as.factor(emotion),
         emotion = droplevels(emotion)) %>% 
  select(participant, emotion, nmes, LPP) %>% 
  group_by(participant, emotion, nmes) %>% 
  summarise(LPP = mean(LPP)) %>% 
  lmer(LPP ~ emotion * nmes + (1 | participant), data = .)

summary(fit_LPP)
anova(fit_LPP, type = 'III')

# post-hoc nmes
emmeans(fit_LPP, pairwise ~ nmes, adjust = "bonferroni")
emmeans(fit_LPP, pairwise ~ nmes, adjust = "bonferroni") %>% confint()
# post-hoc emotion
emmeans(fit_LPP, pairwise ~ emotion, adjust = "bonferroni")
emmeans(fit_LPP, pairwise ~ emotion, adjust = "bonferroni") %>% confint()
```

```{r}
## Remove bad data - this works because all 4 columns have the same bad data
dat2 <- dat2 %>% 
  filter(quality_P1 == 0 |
      quality_N170_left == 0 |
      quality_N170_right == 0 |
      quality_LPP == 0) %>% 
  filter(emotion != 999) %>%
  mutate(
    response = factor(response, levels = c('sad', 'happy')),
    response_n = if_else(response == "happy", 1, 0))
    
## Calculate mean value for participants and nmes where emotion is 1 or -1
mean_10_perc <- dat2 %>%
  filter(!emotion %in% c(-3, 2, -3, -2)) %>%
  group_by(participant, nmes) %>%
  summarise(mean_P1 = mean(P1[emotion %in% c(1, -1)]),
            mean_N170_left = mean(N170_left[emotion %in% c(1, -1)]),
            mean_N170_right = mean(N170_right[emotion %in% c(1, -1)]),
            mean_LPP = mean(LPP[emotion %in% c(1, -1)]),
            mean_resp = mean(response_n[emotion %in% c(1, -1)]))

dat_hap <- compute_emotion("happy", c(1, 2, -1, -2, -3))
dat_sad <- compute_emotion("sad", c(1, 2, 3, -1, -2))

newdat <- full_join(dat_hap, dat_sad) %>%
  mutate(N170 = mean(N170_left, N170_right)) %>%
  select(-N170_left, -N170_right)

options(digits = 6)
t.test(P1 ~ emotion, data = newdat, paired = T)
t.test(N170 ~ emotion, data = newdat, paired = T)
t.test(LPP ~ emotion, data = newdat, paired = T)
```

```{r}
dat_hap <- compute_emotion_2("happy", c(1, 2, -1, -2, -3))
dat_sad <- compute_emotion_2("sad", c(1, 2, 3, -1, -2))

newdat <- full_join(dat_hap, dat_sad) %>%
  mutate(N170_on = mean(N170_left_on, N170_right_on),
         N170_off = mean(N170_left_off, N170_right_off) ) %>%
  select(-N170_left_on, N170_left_off, -N170_right_on, -N170_right_off)

options(digits = 4)
t.test(newdat$P1_on[newdat$emotion == 'happy'], newdat$P1_off[newdat$emotion == 'happy'], paired = TRUE)
t.test(newdat$P1_on[newdat$emotion == 'sad'], newdat$P1_off[newdat$emotion == 'sad'], paired = TRUE)

t.test(newdat$N170_on[newdat$emotion == 'happy'], newdat$N170_off[newdat$emotion == 'happy'], paired = TRUE)
t.test(newdat$N170_on[newdat$emotion == 'sad'], newdat$N170_off[newdat$emotion == 'sad'], paired = TRUE)

t.test(newdat$LPP_on[newdat$emotion == 'happy'], newdat$LPP_off[newdat$emotion == 'happy'], paired = TRUE)
t.test(newdat$LPP_on[newdat$emotion == 'sad'], newdat$LPP_off[newdat$emotion == 'sad'], paired = TRUE)
```

